# Generated by Django 5.1.3 on 2024-12-02 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='cotizaciones.cotizacion')),
            ],
        ),
        migrations.CreateModel(
            name='TareaProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('Impresión', 'Impresión'), ('Acabado', 'Acabado'), ('Empaque', 'Empaque')], max_length=255)),
                ('descripcion', models.TextField()),
                ('completado', models.BooleanField(default=False)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='cotizaciones.cotizacion')),
            ],
        ),
    ]
