# Generated by Django 5.1.3 on 2024-12-02 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=255)),
                ('tipo_encuadernacion', models.CharField(max_length=255)),
                ('imagen', models.URLField(blank=True, null=True)),
                ('plantilla', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
