# Generated by Django 5.1.3 on 2025-05-28 02:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('subcategoria', models.CharField(blank=True, max_length=100)),
                ('tipo_papel', models.CharField(blank=True, choices=[('bond', 'Bond'), ('propalcote', 'Propalcote'), ('opalina', 'Opalina'), ('couche', 'Couché'), ('kraft', 'Kraft'), ('cartulina', 'Cartulina'), ('adhesivo', 'Adhesivo'), ('sintetico', 'Sintético'), ('otro', 'Otro')], max_length=50)),
                ('gramaje', models.PositiveIntegerField(blank=True, help_text='Gramaje del papel (ej: 90, 120, 150)', null=True)),
                ('tamaño', models.CharField(blank=True, help_text='Ej: A4, Carta, 10x15cm, Medio pliego', max_length=100)),
                ('numero_paginas', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo_encuadernacion', models.CharField(blank=True, choices=[('grapado', 'Grapado'), ('espiral', 'Espiral'), ('anillado', 'Anillado'), ('cosido', 'Cosido'), ('pegado', 'Pegado'), ('tapa_dura', 'Tapa Dura'), ('tapa_blanda', 'Tapa Blanda'), ('sin_encuadernacion', 'Sin Encuadernación')], max_length=50)),
                ('acabados_especiales', models.TextField(blank=True, help_text='Describe acabados especiales o personalizados')),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='productos/imagenes/')),
                ('imagenes_adicionales', models.TextField(blank=True, help_text='URLs de imágenes adicionales separadas por comas')),
                ('plantilla_ejemplo', models.FileField(blank=True, null=True, upload_to='productos/plantillas/')),
                ('precio_base', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('atributos_adicionales', models.JSONField(blank=True, default=dict, help_text='Atributos personalizados en formato JSON')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='productos.categoria')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
