# Generated by Django 5.1.3 on 2024-12-05 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecotizacion',
            name='sub_total',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='sub_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
